# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 9 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: abufatih
google_analytics: abufatih

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Abu Fatih Blog
author:
  name: Muhammad Surya Ihsanuddin
#  email: dbyll@ismaildemirbilek.com
  github: ihsanudin
#  twitter: dbtek
#  pinterest: asd123
  linkedin: asd123
  bio: Muhammad Surya Ihsanuddin
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
