# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 9 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: abufatih
google_analytics: abufatih

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Catatan Muhammad Surya Ihsanuddin

description: Catatan Muhammad Surya Ihsanuddin
author:
  name: Muhammad Surya Ihsanuddin
  email: surya.kejawen@gmail.com
  github: ihsanudin
  twitter: ~
  pinterest: ~
  linkedin: ihsanuddin
  bio: Muhammad Surya Ihsanuddin
  email_md5: ~

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
